### ISSUE TITLE
Huge gap with other calculators

### ISSUE THREAD

**Issue by Kwiq** [superbob/clicker-heroes-1.0-hsoptimizer#11]
Hi, i just found your optimizer and i see it recommands me to raise Solomon like 50% more than the Kepow does for example. 
It tells me to put 16K levels in Solomon while Kepow's 'only' 11K.
The gap between this calculator and the others is pretty confusing to me.

**Comment by superbob** [comment]
It's beta, there may be some miscalculations... In fact I would have expect recommendations for Solomon to be a little bit lower than kepow ...

Moreover Solomon leveling is tricky because fast optimization require approximations...
Without these approximation it would take too long to compute it.

Can you provide a savefile? (You should clean up any email, account and clan data before posting it).

**Comment by Kwiq** [comment]
Voilà ! 
[http://pastebin.com/0PPGCFyS](http://pastebin.com/0PPGCFyS)
Thank you a lot for your job, i'm gonna still using it and looking at for a while ;)

**Comment by JourneyOver** [comment]
@Kwiq I'd say it's better to upload your save to something like pastebin.com as I think the google docs ends up making break lines in the save so it wouldn't be able to do imports correctly.

**Comment by superbob** [comment]
Perfect ! 👍

**Comment by Kwiq** [comment]
Glad to help

**Comment by superbob** [comment]
The problem has been identified and will be fixed in #12

**Comment by Kingslayer23** [comment]
how to join a clan

**Comment by superbob** [comment]
I'm sorry I don't understand your question.
How does it relate to calculator or this particular issue?
If you're asking a question about game mechanics, you should ask on Reddit.
